apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000        # Port exposed by the service
      targetPort: 3000  # Port your Node.js app listens on
  type: NodePort        # Makes it accessible from outside the cluster
