apiVersion: v1
kind: Service
metadata:
  name: node-deployment
  namespace: default
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - port: 3000        # Port inside the cluster
      targetPort: 3000  # Port your Node.js app listens on in the pod
      nodePort: 30080   # Port exposed on Minikube node
      protocol: TCP
